/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ContainerImage model module.
* @module model/ContainerImage
* @version 0.0.1
*/
export default class ContainerImage {
    /**
    * Constructs a new <code>ContainerImage</code>.
    * @alias module:model/ContainerImage
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ContainerImage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerImage} obj Optional instance to populate.
    * @return {module:model/ContainerImage} The populated <code>ContainerImage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerImage();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('source_created_at')) {
                obj['source_created_at'] = ApiClient.convertToType(data['source_created_at'], 'Date');
            }
            if (data.hasOwnProperty('source_deleted_at')) {
                obj['source_deleted_at'] = ApiClient.convertToType(data['source_deleted_at'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} tag
    */
    tag = undefined;
    /**
    * @member {Date} source_created_at
    */
    source_created_at = undefined;
    /**
    * @member {Date} source_deleted_at
    */
    source_deleted_at = undefined;








}


