/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Container model module.
* @module model/Container
* @version 0.0.1
*/
export default class Container {
    /**
    * Constructs a new <code>Container</code>.
    * @alias module:model/Container
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Container</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Container} obj Optional instance to populate.
    * @return {module:model/Container} The populated <code>Container</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Container();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cpu_limit')) {
                obj['cpu_limit'] = ApiClient.convertToType(data['cpu_limit'], 'Number');
            }
            if (data.hasOwnProperty('cpu_request')) {
                obj['cpu_request'] = ApiClient.convertToType(data['cpu_request'], 'Number');
            }
            if (data.hasOwnProperty('memory_limit')) {
                obj['memory_limit'] = ApiClient.convertToType(data['memory_limit'], 'Number');
            }
            if (data.hasOwnProperty('memory_request')) {
                obj['memory_request'] = ApiClient.convertToType(data['memory_request'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Number} cpu_limit
    */
    cpu_limit = undefined;
    /**
    * @member {Number} cpu_request
    */
    cpu_request = undefined;
    /**
    * @member {Number} memory_limit
    */
    memory_limit = undefined;
    /**
    * @member {Number} memory_request
    */
    memory_request = undefined;








}


