/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Endpoint model module.
* @module model/Endpoint
* @version 0.0.1
*/
export default class Endpoint {
    /**
    * Constructs a new <code>Endpoint</code>.
    * @alias module:model/Endpoint
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Endpoint</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Endpoint} obj Optional instance to populate.
    * @return {module:model/Endpoint} The populated <code>Endpoint</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Endpoint();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('scheme')) {
                obj['scheme'] = ApiClient.convertToType(data['scheme'], 'String');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {Boolean} default
    */
    default = undefined;
    /**
    * URI host component
    * @member {String} host
    */
    host = undefined;
    /**
    * URI path component
    * @member {String} path
    */
    path = undefined;
    /**
    * URI port component
    * @member {Number} port
    */
    port = undefined;
    /**
    * @member {String} role
    */
    role = undefined;
    /**
    * URI scheme component
    * @member {String} scheme
    */
    scheme = undefined;
    /**
    * @member {String} source_id
    */
    source_id = undefined;
    /**
    * @member {String} tenant_id
    */
    tenant_id = undefined;








}


