/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Flavor model module.
* @module model/Flavor
* @version 0.0.1
*/
export default class Flavor {
    /**
    * Constructs a new <code>Flavor</code>.
    * @alias module:model/Flavor
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Flavor</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Flavor} obj Optional instance to populate.
    * @return {module:model/Flavor} The populated <code>Flavor</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Flavor();

            
            
            

            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('disk_size')) {
                obj['disk_size'] = ApiClient.convertToType(data['disk_size'], 'Number');
            }
            if (data.hasOwnProperty('disk_count')) {
                obj['disk_count'] = ApiClient.convertToType(data['disk_count'], 'Number');
            }
            if (data.hasOwnProperty('memory')) {
                obj['memory'] = ApiClient.convertToType(data['memory'], 'Number');
            }
            if (data.hasOwnProperty('cpus')) {
                obj['cpus'] = ApiClient.convertToType(data['cpus'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} source_ref
    */
    source_ref = undefined;
    /**
    * Size of the default disks in bytes
    * @member {Number} disk_size
    */
    disk_size = undefined;
    /**
    * The number of default disks
    * @member {Number} disk_count
    */
    disk_count = undefined;
    /**
    * Amount of RAM in bytes
    * @member {Number} memory
    */
    memory = undefined;
    /**
    * Number of CPUs
    * @member {Number} cpus
    */
    cpus = undefined;








}


