/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Id model module.
* @module model/Id
* @version 0.0.1
*/
export default class Id {
    /**
    * Constructs a new <code>Id</code>.
    * @alias module:model/Id
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Id</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Id} obj Optional instance to populate.
    * @return {module:model/Id} The populated <code>Id</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Id();

            
            
            

        }
        return obj;
    }









}


