/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ServiceParametersSet model module.
* @module model/ServiceParametersSet
* @version 0.0.1
*/
export default class ServiceParametersSet {
    /**
    * Constructs a new <code>ServiceParametersSet</code>.
    * @alias module:model/ServiceParametersSet
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ServiceParametersSet</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServiceParametersSet} obj Optional instance to populate.
    * @return {module:model/ServiceParametersSet} The populated <code>ServiceParametersSet</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceParametersSet();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('extra')) {
                obj['extra'] = ApiClient.convertToType(data['extra'], Object);
            }
            if (data.hasOwnProperty('source_created_at')) {
                obj['source_created_at'] = ApiClient.convertToType(data['source_created_at'], 'Date');
            }
            if (data.hasOwnProperty('source_deleted_at')) {
                obj['source_deleted_at'] = ApiClient.convertToType(data['source_deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('service_offering_id')) {
                obj['service_offering_id'] = ApiClient.convertToType(data['service_offering_id'], 'String');
            }
            if (data.hasOwnProperty('create_json_schema')) {
                obj['create_json_schema'] = ApiClient.convertToType(data['create_json_schema'], Object);
            }
            if (data.hasOwnProperty('update_json_schema')) {
                obj['update_json_schema'] = ApiClient.convertToType(data['update_json_schema'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Object} extra
    */
    extra = undefined;
    /**
    * @member {Date} source_created_at
    */
    source_created_at = undefined;
    /**
    * @member {Date} source_deleted_at
    */
    source_deleted_at = undefined;
    /**
    * @member {String} source_id
    */
    source_id = undefined;
    /**
    * @member {String} source_ref
    */
    source_ref = undefined;
    /**
    * @member {String} tenant_id
    */
    tenant_id = undefined;
    /**
    * @member {String} service_offering_id
    */
    service_offering_id = undefined;
    /**
    * @member {Object} create_json_schema
    */
    create_json_schema = undefined;
    /**
    * @member {Object} update_json_schema
    */
    update_json_schema = undefined;








}


