/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Vm model module.
* @module model/Vm
* @version 0.0.1
*/
export default class Vm {
    /**
    * Constructs a new <code>Vm</code>.
    * @alias module:model/Vm
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Vm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Vm} obj Optional instance to populate.
    * @return {module:model/Vm} The populated <code>Vm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Vm();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('source_created_at')) {
                obj['source_created_at'] = ApiClient.convertToType(data['source_created_at'], 'Date');
            }
            if (data.hasOwnProperty('source_deleted_at')) {
                obj['source_deleted_at'] = ApiClient.convertToType(data['source_deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('uid_ems')) {
                obj['uid_ems'] = ApiClient.convertToType(data['uid_ems'], 'String');
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('power_state')) {
                obj['power_state'] = ApiClient.convertToType(data['power_state'], 'String');
            }
            if (data.hasOwnProperty('cpus')) {
                obj['cpus'] = ApiClient.convertToType(data['cpus'], 'Number');
            }
            if (data.hasOwnProperty('memory')) {
                obj['memory'] = ApiClient.convertToType(data['memory'], 'Number');
            }
            if (data.hasOwnProperty('orchestration_stack_id')) {
                obj['orchestration_stack_id'] = ApiClient.convertToType(data['orchestration_stack_id'], 'String');
            }
            if (data.hasOwnProperty('flavor_id')) {
                obj['flavor_id'] = ApiClient.convertToType(data['flavor_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * Description of the Vm
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Date} source_created_at
    */
    source_created_at = undefined;
    /**
    * @member {Date} source_deleted_at
    */
    source_deleted_at = undefined;
    /**
    * @member {String} source_id
    */
    source_id = undefined;
    /**
    * @member {String} source_ref
    */
    source_ref = undefined;
    /**
    * @member {String} tenant_id
    */
    tenant_id = undefined;
    /**
    * Cross-Source Unique Reference
    * @member {String} uid_ems
    */
    uid_ems = undefined;
    /**
    * @member {String} hostname
    */
    hostname = undefined;
    /**
    * @member {String} power_state
    */
    power_state = undefined;
    /**
    * Total number of CPUs
    * @member {Number} cpus
    */
    cpus = undefined;
    /**
    * Total RAM in bytes
    * @member {Number} memory
    */
    memory = undefined;
    /**
    * @member {String} orchestration_stack_id
    */
    orchestration_stack_id = undefined;
    /**
    * @member {String} flavor_id
    */
    flavor_id = undefined;








}


