/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The VolumeType model module.
* @module model/VolumeType
* @version 0.0.1
*/
export default class VolumeType {
    /**
    * Constructs a new <code>VolumeType</code>.
    * @alias module:model/VolumeType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>VolumeType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VolumeType} obj Optional instance to populate.
    * @return {module:model/VolumeType} The populated <code>VolumeType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VolumeType();

            
            
            

            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} source_ref
    */
    source_ref = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} description
    */
    description = undefined;








}


