/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Volume model module.
* @module model/Volume
* @version 0.0.1
*/
export default class Volume {
    /**
    * Constructs a new <code>Volume</code>.
    * @alias module:model/Volume
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Volume</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Volume} obj Optional instance to populate.
    * @return {module:model/Volume} The populated <code>Volume</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Volume();

            
            
            

            if (data.hasOwnProperty('source_region_id')) {
                obj['source_region_id'] = ApiClient.convertToType(data['source_region_id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('source_created_at')) {
                obj['source_created_at'] = ApiClient.convertToType(data['source_created_at'], 'Date');
            }
            if (data.hasOwnProperty('source_deleted_at')) {
                obj['source_deleted_at'] = ApiClient.convertToType(data['source_deleted_at'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} source_region_id
    */
    source_region_id = undefined;
    /**
    * @member {String} source_ref
    */
    source_ref = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} state
    */
    state = undefined;
    /**
    * Size of the volume in bytes
    * @member {Number} size
    */
    size = undefined;
    /**
    * @member {Date} source_created_at
    */
    source_created_at = undefined;
    /**
    * @member {Date} source_deleted_at
    */
    source_deleted_at = undefined;








}


